num_classes: 10
epochs: 100
log_frequency: 100
warmup_epochs: 10
blr_scale: linear
blr: 0.4
lr: 0.4
min_lr: 0.0
sync_bn: true
lr_schedule: cosine
snapshot_epoch: 25
eval_every_epoch: 1
full_set_lid_eval: false
weight_decay: 1.5e-06
amp: true
momentum_tau: 0.99
momentum_tau_schedule: byol
criterion:
  name: BYOLLIDReg
  gather_distributed: true
  alpha: 0.005
  est_type: mom
  lid_type: f
  reg_type: l1
  warmup_epochs: 10
  k: 32
model:
  name: ResNetBYOL
  block_type: bottleneck
  num_blocks:
  - 3
  - 4
  - 6
  - 3
  c_k: 7
  projection_dim: 256
  get_features: true
  use_bias: true
optimizer:
  name: LARS
  lr: $lr
  weight_decay: 1.5e-06
  momentum: 0.9
dataset:
  name: DatasetGenerator
  train_bs: 512
  eval_bs: 512
  n_workers: 8
  train_d_type: ImageFolder
  test_d_type: ImageFolder
  train_tf_op: VICReg
  test_tf_op: ImageNet
  train_path: /data/scratch/datasets/ImageNet/ILSVRC/Data/CLS-LOC
  test_path: /data/scratch/datasets/ImageNet/ILSVRC/Data/CLS-LOC
  collate_fn:
    name: None
