num_classes: 1000
epochs: 200
log_frequency: 100
warmup_epochs: 20
blr: 1.5e-4
lr: 1.5e-4
blr_scale: linear
min_lr: 0
sync_bn: true
lr_schedule: cosine
snapshot_epoch: 25
eval_every_epoch: 1
full_set_lid_eval: false
amp: true
weight_decay: 0.1
criterion:
  name: NTXentLoss
  temperature: 0.2
  gather_distributed: true
model:
  name: simclr_vit_base_patch16
  stop_grad_conv1: true
  get_features: true
optimizer:
  name: AdamW
  lr: $lr
  weight_decay: 0.1
dataset:
  name: DatasetGenerator
  train_bs: 256
  eval_bs: 256
  n_workers: 8
  train_d_type: ImageFolder
  test_d_type: ImageFolder
  train_tf_op: VICReg
  test_tf_op: ImageNet
  train_path: /data/scratch/datasets/ImageNet/ILSVRC/Data/CLS-LOC
  test_path: /data/scratch/datasets/ImageNet/ILSVRC/Data/CLS-LOC
  collate_fn:
    name: None