_BASE_: "coco_R_50_C4_2x.yaml"
MODEL:
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [1.0, 1.0, 1.0]
  WEIGHTS: "/path/to/your/*.pkl"
  RESNETS:
    STRIDE_IN_1X1: False
INPUT:
  FORMAT: "RGB"
OUTPUT_DIR: '/path/to/your/experiments/'
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.02