num_classes: 1000
epochs: 200
log_frequency: 100
warmup_epochs: 40
blr: 1.5e-4
lr: 1.5e-4
blr_scale: linear
min_lr: 0
sync_bn: true
lr_schedule: cosine
snapshot_epoch: 25
eval_every_epoch: 1
amp: true
weight_decay: 0.05
criterion:
  name: MAELoss
model:
  name: mae_vit_base_patch16_dec512d8b
  norm_pix_loss: true
optimizer:
  name: AdamW
  lr: $lr
  weight_decay: $weight_decay
  betas:
  - 0.9
  - 0.95
dataset:
  name: DatasetGenerator
  train_bs: 512
  eval_bs: 512
  n_workers: 8
  train_d_type: ImageFolder
  test_d_type: ImageFolder
  train_tf_op: ImageNetMAE
  test_tf_op: ImageNetMAE
  train_path: /data/scratch/datasets/ImageNet/ILSVRC/Data/CLS-LOC
  test_path: /data/scratch/datasets/ImageNet/ILSVRC/Data/CLS-LOC
  collate_fn:
    name: None
